stages:
  - build

build:
  stage: build
  image: python:3.9-slim
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache: # https://docs.gitlab.com/ee/ci/caching/#cache-python-dependencies
    paths:
      - .cache/pip
      - .venv/
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - python -m pip install -r requirements.txt
    - python -m pip install pyinstaller
  script:
    - pyinstaller --onefile --name MeadDesigner src/main.py
  artifacts:
    paths:
      - dist