stages:
  - build

build:
  stage: build
  image: 
    name: batonogov/pyinstaller-windows:latest
    entrypoint: ['']
  script:
    - echo "Creating Windows artifact"
    - pip install -r ./requirements.txt
    - pyinstaller --onefile main.py
  artifacts:
    paths:
      - dist